from enum import Enum

class StatesVariant(Enum):
    INITIAL_ONLY = 1
    INITIAL_CONTRADICTORY = 2
    INITIAL_CONTRARY = 3
    INITIAL_SUBALTERNATE = 4
    INITIAL_CONTRARY_CONTRADICTORY = 5
    INITIAL_SUBALTERNATE_CONTRADICTORY = 6
    INITIAL_CONTRARY_SUBALTERNATE = 7
    ALL_PREDICATES = 8